on:
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-slim
    steps:
      - run: |
          echo "Hello from main job"

  reusable:
    uses: .github/workflows/reusable.yaml
    with:
      dry-run: true
